### ISSUE TITLE
How to calculate total cost of a workflow including execution cost and communication cost

### ISSUE THREAD

**Issue by Bhopender** [WorkflowSim/WorkflowSim-1.0#20]
how can we take total cost as a fitness function in a meta-heuristic algorithm?
total cost= execution cost(resource)+communication cost or transfer cost(resource)

**Comment by chenww05** [comment]
Just use https://github.com/WorkflowSim/WorkflowSim-1.0/blob/master/examples/org/workflowsim/examples/planning/HEFTPlanningAlgorithmExample1.java as an example to do it. Modify it as you like.
